Dynamic secret support
Infisical/go-sdk pull request #15
Opened 2024-10-24 16:08 UTC by akhilmhdh

This PR brings support to dynamic secret leasing and listing dynamic secret root credentials.  This is phase 1 to support same in CLI. 

Root credentials management is still not addded to sdk, and not planning to the CLI as well for time being. 

The plan is for now root cred management happens in UI and customers use CLI to lease and get temporary credentials.

2024-10-24 16:18 UTC, DanielHougaard requested changes
Looks good! Left a few comments

2024-10-24 16:18 UTC, DanielHougaard commented on client.go
> +	client.dynamicSecrets = NewDynamicSecrets(client)
If we're going to introduce this new pattern of `NewResourceName(client)`, can you please add it for the others as well? secrets, folders, and auth.

2024-10-24 16:18 UTC, DanielHougaard commented on dynamic_secrets.go
> +	ListRootCredentials(options ListDynamicSecretsRootCredentialsOptions) ([]models.DynamicSecret, error)
I think a structure that would be good for this, would be:

`client.dynamicSecrets().Leases().List`
`client.dynamicSecrets().Leases().Create`
... etc (this is also the structure we use in the new Node SDK)

This is how we do it for secrets, so to keep things consistant we should also do this for dynamic secrets.

2024-10-24 16:18 UTC, DanielHougaard commented on dynamic_secrets.go
> +func (f *DynamicSecrets) CreateLease(options CreateDynamicSecretLeaseOptions) (map[string]any, models.DynamicSecret, models.DynamicSecretLease, error) {
`map[string]any`, do we not know the type for this? could we perhaps parse it so we can give the user type-safety?

2024-10-24 16:31 UTC, akhilmhdh commented on dynamic_secrets.go
> +	ListRootCredentials(options ListDynamicSecretsRootCredentialsOptions) ([]models.DynamicSecret, error)
Ohh ok

2024-10-24 16:32 UTC, akhilmhdh commented on dynamic_secrets.go
> +func (f *DynamicSecrets) CreateLease(options CreateDynamicSecretLeaseOptions) (map[string]any, models.DynamicSecret, models.DynamicSecretLease, error) {
Actually we should not. Because recently realized these things are better keeping it unstructured because the data is very much different compared to each dynamic secret provider.

Also if we type it out for each new provider we would also have to make new release as it will break older clients for supported leasing

2024-10-24 16:33 UTC, akhilmhdh commented on client.go
> +	client.dynamicSecrets = NewDynamicSecrets(client)
Sure.

2024-10-24 16:45 UTC, akhilmhdh commented on client.go
> +	client.dynamicSecrets = NewDynamicSecrets(client)
Updated.

2024-10-24 16:45 UTC, akhilmhdh commented on dynamic_secrets.go
> +	ListRootCredentials(options ListDynamicSecretsRootCredentialsOptions) ([]models.DynamicSecret, error)
Changed to above structure

2024-10-25 12:04 UTC, DanielHougaard approved these changes

2024-10-25 12:04 UTC, merged